# nlp task_types colud be(follwing huggingface transformers implementation)
# CausalLM, Seq2SeqLM, MaskedLM, NextSentencePrediction, QuestionAnswering,
# SequenceClassification, TokenClassification

[[tasks]]
name = "klue"
sub_tasks = ["ynat", "sts", "nli", "ner", "mrc"]
task_types = [
    "SequenceClassification",
    "SequenceClassification",
    "SequenceClassification",
    "TokenClassification",
    "TokenClassification",
]
label_keys = ["label","labels__binary-label", "label", "ner_tags"]

[[tasks]]
name = "kor_sarcasm"
task_types = ["SequenceClassification"]
label_keys = []

[[tasks]]
name = "kor_sarcasm"
task_types = ["SequenceClassification"]
label_keys = []

[[tasks]]
name = "kor_nlu"
sub_tasks = ["nli", "sts"]
task_types = ["SequenceClassification", "SequenceClassification"]
label_keys = []

[[tasks]]
name = "skt/kobest_v1"
sub_tasks = ["boolq", "copa", "sentineg", "hellaswag", "wic"]
task_types = [
    "SequenceClassification",
    "SequenceClassification",
    "SequenceClassification",
    "SequenceClassification",
    "SequenceClassification",
]
label_keys = []

[[tasks]]
name = "kor_sarcasm"
task_types = ["SequenceClassification"]
label_keys = []

[[tasks]]
name = "kor_sae"
task_types = ["SequenceClassification"]
label_keys = []

[[tasks]]
name = "squad_kor_v1"
task_types = ["QuestionAnswering"]

[[tasks]]
name = "mteb/amazon_massive_intent"
task_types = ["SequnceClassification"]
label_keys = []
[[tasks]]
name = "paws"
sub_tasks = ["labeled_final"]
task_types = ["SequenceClassification"]
label_keys = []
