# nlp task_types: colud be(follwing huggingface transformers implementation)
# CausalLM, Seq2SeqLM, MaskedLM, NextSentencePrediction, QuestionAnswering,
# SequenceClassification, TokenClassification, Regression

# sources: huggingface_datasets, korpora


[[tasks]]
name = "klue"
sub_tasks = ["ynat", "sts", "nli", "ner"]
task_types = [
    "SequenceClassification",
    "SequenceClassification",
    "SequenceClassification",
    "TokenClassification",
]
feature_keys = [["title"],["sentence1","sentence2"],["premise","hypothesis"],["sentence"]]
label_keys = ["label","labels__binary-label", "label", "ner_tags"]

[[tasks]]
name = "kor_sarcasm"
task_types = ["SequenceClassification"]
feature_keys = [["tokens"]]
label_keys = ["label"]

[[tasks]]
name = "kor_nlu"
sub_tasks = ["nli", "sts"]
task_types = ["SequenceClassification", "Regression"]
feature_keys = [["premise","hypothesis"],["sentence1","sentence2"]]
label_keys = ["label","score"]

[[tasks]]
name = "skt/kobest_v1"
sub_tasks = ["boolq", "copa", "sentineg", "hellaswag", "wic"]
task_types = [
    "SequenceClassification",
    "SequenceClassification",
    "SequenceClassification",
    "SequenceClassification",
    "SequenceClassification",
]
feature_keys= [["paragraph","question"],["premise","question","alternative_1","alternative_2"],["sentence"],["context","ending_1","ending_2","ending_3","ending_4"],["word","context_1","context_2"]]
label_keys = ["label","label","label","label","label"]

[[tasks]]
name = "kor_sae"
task_types = ["SequenceClassification"]
feature_keys = [["intent_pair1","intent_pair2"]]
label_keys = ["label"]

[[tasks]]
name = "squad_kor_v1"
task_types = ["QuestionAnswering"]

[[tasks]]
name = "mteb/amazon_massive_intent"
task_types = ["SequnceClassification"]
label_keys = ["label"]

[[tasks]]
name = "paws"
sub_tasks = ["labeled_final"]
task_types = ["SequenceClassification"]
feature_keys = [["sentence1","sentence2"]]
label_keys = ["label"]

[[tasks]]
source = "korpora"
name = "nsmc"
task_types = ["SequenceClassification"]
feature_keys = [["text"]]
label_keys = ["label"]

[[tasks]]
source = "korpora"
name = "question_pair"
task_types = ["SequenceClassification"]
feature_keys = [["text","pair"]]
label_keys = ["label"]

[[tasks]]
source = "korpora"
name = "korean_petitions"
task_types = ["SequenceClassification"]
feature_keys = [["text","title"]]
label_keys = ["category"]
